name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.13
  - pip
  - pip:
      - pandas
      - numpy
      - matplotlib
      - seaborn
      - statsmodels
      - scikit-learn
      - scipy
      - holidays
      - networkx
      - jupyter
      - ipykernel
      - albumentations
      - opencv-python
      - scikit-image
      - datasets
      - imagehash
      - missingno
      - imblearn
      - arch